### ISSUE TITLE
Jojo's Doubts

### ISSUE THREAD

**Issue by faitdivers** [smiranda/rl1k-dev#1]
1. Why are we using Phaser.Canvas instead of Phaser.AUTO? Is there any problem with using WebGL?
2. Why not turn this "var phaserh = this;" into a global variable?
3. Why do we have a difference between "phaserh.game" and "engine"? Couldn't we have a single entity?
4. Why is the bot layer inside the map layer? 
   The map layer and the bot layer should be restarted upon entering a portal/door.
   The map layer has been (at the moment) already created.
   The bot layer can be already defined with the map. If their creation is random can't we, in the engine update phase, call a collide routine such that they don't end up in places where they shouldn't?
5. Why is:
       engine.player = BotModule.CreateBot('bot');
       engine.portal = PortalModule.CreatePortal('portal');
   inside Preload, instead of Create?
6. What is the advantage of createBodyCallback over a collision detection routine in the Update phase of the Engine?

Feel free to answer/delete/transform these questions into separate issues.

**Comment by smiranda** [comment]
(5.) That can be moved to Create
(6.) You only have to create the callback createBodyCallback once. Phaser handles colisions internally and calls your callback assynchronously. Probably there's some synchronous way to handle colisions, that's just some approach i found somewhere.

**Comment by smiranda** [comment]
(2.) Yes, you could assign 'this' to a global variable in the Preload function. 'this' points to the callee context. In the  Engine.prototype.Create/Preload/Render/Update that will point to the phaser object, so yes you could store that once. Keep in mind that this is a special case, since these functions are being called from the context of another object. In our other classes, 'this' refers to the object instance, since the functions are called as instance methods.

**Comment by smiranda** [comment]
(3.) phaserh (or the callee context 'this' on those main functions), is the library main state object. 'engine' is our own object. Since JS allows you to live the fat life, you could plug new properties and methods into the phaser object. But because I felt dirty doing that, I thought it would be better to use an object of our own to register the game state, and use the phaser object just for the lib stuff.

**Comment by smiranda** [comment]
(4.) Since I believe we won't jump into procedural generation immediately, I though we could start by using hand-made maps. To that end, we are using a tool caled 'Tiled', and we are also specifying where the bots should be, using that same map editor. The 'bots' layer in the map is just for seeding the bot's starting position. Then they become independent phaser sprites/bodies.

**Comment by vascop** [comment]
Each concern should have its separate issue!
